# -*- coding: utf-8 -*-
"""DL assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIVdMQGrscGpxVeXX6r3H3WjAPaIdJcJ

Linear regression by using Deep Neural network: Implement Boston housing price predictionproblem by Linear regression using Deep Neural network. Use Boston House price prediction 
dataset
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

boston = pd.read_csv('./boston.csv')
boston.head()

X = boston.iloc[:, boston.columns != "MEDV"]
y = boston.iloc[:, boston.columns == "MEDV"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 123)

model = Sequential([
    Dense(128, input_shape=(13, ), activation="relu", name="dense1"), 
    Dense(64, activation="relu",name="dense2"), 
    Dense(1, activation="linear", name="output") 
])
model.compile(optimizer="adam", loss='mse', metrics=['mae'])
model.summary()

history = model.fit(X_train, y_train, epochs=100)

mse_nn, mae_nn = model.evaluate(X_test, y_test)
print("MSE:", mse_nn)
print("MAE:", mae_nn)